version: "3.8"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "18080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    command:
      - start-dev
    depends_on:
      - postgresql
    networks:
      auth:

  postgresql:
    container_name: postgresql
    image: postgres:13-alpine3.14
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Asia/Tokyo"
    ports:
      - "65432:5432"
    user: root
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      auth:

networks:
  auth:

volumes:
  postgresql: